### PR TITLE
PostCSS 6

### PR DESCRIPTION
**Pull request by borodean**
Resolves https://github.com/borodean/postcss-assets/issues/70 and https://github.com/borodean/postcss-assets/issues/71.

### CODE REVIEW

**Comment by onigoetz** [comment]
Hi,

Is there something I can do to help make this work ?

**Comment by borodean** [comment]
@onigoetz it's waiting for postcss-functions to publish its upgrade to PostCSS 6 on NPM https://github.com/andyjansson/postcss-functions/pull/20

**Comment by onigoetz** [comment]
Hi @borodean, postcss-functions 3.0.0 has been released :)

**Comment by borodean** [comment]
@onigoetz thanks for letting know! Merged and released in `postcss-assets@5.0.0`.

**Comment by onigoetz** [comment]
awesome, thanks :)

**Pull request merged**
