### PR TITLE
Fix SVG encoding

### PR DESCRIPTION
**Pull request by demiazz**
@borodean, hi! I'm fix generation inline SVG. I use library, which use postcss-url, and them generate safety not corrupted dataURI.

And I fix fixtures. But I found strange behaviour. PostCSS may generate or may not `'` in url. @ai, can you comment this?

### CODE REVIEW

**Comment by ai** [comment]
Yeap. This should fix SVG issues.

**Comment by ai** [comment]
@borodean any updates? We will suggest your tool on our Brainwashing workshop and SVG escape bug is very important.

**Comment by borodean** [comment]
@ai, @demiazz, could you please provide a more broad explanation of what this issue is?

**Comment by ai** [comment]
@demiazz can you add that SVG, that broke your styles after inlining?

I saw that some images are broke CSS in postcss-assets. But postcss-url inlines them without any problems. So I think that we need just copy postcss-url SVG escape if we sure, that it works.

**Comment by niksy** [comment]
I’ve noticed the problem in Firefox, and after applying this fix everything works fine.

**Comment by demiazz** [comment]
https://gist.github.com/demiazz/7b11535b33a852622a42

For example, one of many files, which has been incorrect inlined with utf-8 encoding.

**Comment by borodean** [comment]
@demiazz could you please do a similar pull request, but against `develop`? This repo is following [git-flow methodology](http://nvie.com/posts/a-successful-git-branching-model/) so pushing features directly would bring some mess.

**Comment by demiazz** [comment]
Ок. And I will merge all commits in one.

**Comment by borodean** [comment]
@demiazz I can do it myself and release tomorrow, what do you think?

**Comment by borodean** [comment]
@demiazz, sorry, I’ve just realized that your fix fits gitflow, because it’s of a hotfix kind.

**Pull request merged**
