### PR TITLE
Add `cache` option

### PR DESCRIPTION
**Pull request by booxood**

### CODE REVIEW

**Comment by borodean** [comment]
@booxood that's sweet! Actually, I wanted it to have some caching since forever. The better place for the implementation might be the core library (https://github.com/borodean/assets), however, I think it's fine here for now.

But what do you think about renaming that option name to just `cache`? So when and if some other caching is implemented the API wouldn't change.

**Comment by booxood** [comment]
@borodean I think `cache ` is appropriate. I'll make some changes.

**Comment by borodean** [comment]
@booxood I'm preparing the release now. I'm usually adding everyone who's contributing to the project under the `contributors` section of `package.json`. Since I don't know your name, I'll add you as `Liucw (https://github.com/booxood)` just as your Github profile says. Is this okay?

**Comment by booxood** [comment]
@borodean OK. It's my pleasure. :stuck_out_tongue_closed_eyes:

**Comment by borodean** [comment]
Published `postcss-assets@4.2.0`.

**Comment by booxood** [comment]
:tada::tada::tada:

**Pull request merged**
